eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8763
spring:
  application:
    name: service-exhibition

spring:
  rabbitmq:
     host: localhost

spring:
  rabbitmq:
     port: 5672
spring:
  rabbitmq:
     username: guest
spring:
  rabbitmq:
     password: guest